### ISSUE TITLE
can soanr-objective-c support 6.5?

### ISSUE THREAD

**Issue by RogerAbyss** [Backelite/sonar-objective-c#43] opened 2017-09-11 08:44 UTC
I use docker file to build sonarqube, it is 6.5.but seems sonar-objective-c 0.6.1 do not support yet.

**Comment by JackLeo** [comment] 2017-09-11 13:06
AFAIK this is duplicate of https://github.com/Backelite/sonar-objective-c/issues/39

**Comment by andrewclaus** [comment] 2017-11-09 17:59
I was able to get the plugin working with Sonar 6.5 the change in my pull request here: https://github.com/Backelite/sonar-objective-c/pull/48

**Comment by zippy1978** [comment] 2017-12-06 08:24
Hi all,

Version 0.6.2 of the plugin now works with SonarQube 6.5.

Regards,
Gilles

**Closed as completed by zippy1978** 2017-12-06 08:24 UTC
